Fixes for #1209
zalando/zally pull request #1210
Opened 2021-03-02 08:36 UTC by tharakadesilva

2021-03-05 16:36 UTC, tkrop commented
:+1:

2021-03-05 17:49 UTC, vadeg requested changes
Hi @tharakadesilva !

Thank you for your contribution, but I don't think that `ReverseAst` is the right place to define `paths` property. This is a part of OpenAPI / Swagger spec. I think it should be somewhere in the `Context` or as an extension for `OpenAPI` or `Swagger` classes.

2021-03-05 17:49 UTC, vadeg commented on server/zally-core/src/main/kotlin/org/zalando/zally/core/ast/ReverseAst.kt
> +        const val pathsJsonPointerString = "/paths"
Please follow [kotlin guidelines](https://kotlinlang.org/docs/coding-conventions.html#property-names) for naming.

2021-03-05 17:49 UTC, vadeg commented on server/zally-core/src/main/kotlin/org/zalando/zally/core/ast/ReverseAst.kt
> +        val pathsJsonPointer = pathsJsonPointerString.toJsonPointer()
Same here about Kotlin guidelines.

2021-03-06 20:19 UTC, tharakadesilva commented on server/zally-core/src/main/kotlin/org/zalando/zally/core/ast/ReverseAst.kt
> +        const val pathsJsonPointerString = "/paths"
Fixed.

2021-03-06 20:19 UTC, tharakadesilva commented on server/zally-core/src/main/kotlin/org/zalando/zally/core/ast/ReverseAst.kt
> +        val pathsJsonPointer = pathsJsonPointerString.toJsonPointer()
Fixed.

2021-03-06 20:27 UTC, tharakadesilva commented
> Hi @tharakadesilva !
> 
> Thank you for your contribution, but I don't think that `ReverseAst` is the right place to define `paths` property. This is a part of OpenAPI / Swagger spec. I think it should be somewhere in the `Context` or as an extension for `OpenAPI` or `Swagger` classes.

Hi @vadeg, thank you for the feedback. I am a little torn on where to move these. I feel that the recommendation to move it as an extension to `OpenAPI` is the best approach. `OpenAPI` already has some extensions in the `OpenApiUtil.kt` file. Do you think that this might be a good place to place these values as well?

2021-03-11 21:50 UTC, vadeg commented
@tharakadesilva I would suggest something like this
```
class OpenApiPaths {
    companion object {
        const val PATHS = "/paths"
    }
}
```
Unfortunately, Kotlin [doesn't support](https://youtrack.jetbrains.com/issue/KT-11968) static extensions for Java classes and the original idea to make someting like 
```
io.swagger.v3.oas.models.Paths
val Paths.paths: String 
    get() = "sdafa"
```
and use like `Paths.paths` will not work.

2021-03-13 18:13 UTC, tharakadesilva commented
@vadeg I have fixed the code as you suggested. Would appreciate it if you could review it again now.

2021-03-15 20:38 UTC, vadeg reviewed
Hi @tharakadesilva 

Sorry for the delay. I have left a couple of comments.

2021-03-15 20:38 UTC, vadeg commented on server/zally-core/src/main/kotlin/org/zalando/zally/core/util/OpenApiPaths.kt
> +        val PATHS_JSON_POINTER = PATHS_JSON_POINTER_STRING.toJsonPointer()
I thinks this is not needed here, because it is up to the client how to interpret the string.

2021-03-15 20:38 UTC, vadeg commented on server/zally-core/src/main/kotlin/org/zalando/zally/core/util/OpenApiPaths.kt
> +        const val PATHS_JSON_POINTER_STRING = "/paths"
This is not a JSON pointer but a json path. Could you rename it to `PATHS`?

2021-03-16 09:38 UTC, tharakadesilva commented on server/zally-core/src/main/kotlin/org/zalando/zally/core/util/OpenApiPaths.kt
> +        val PATHS_JSON_POINTER = PATHS_JSON_POINTER_STRING.toJsonPointer()
I have removed this.

2021-03-16 09:40 UTC, tharakadesilva commented on server/zally-core/src/main/kotlin/org/zalando/zally/core/util/OpenApiPaths.kt
> +        const val PATHS_JSON_POINTER_STRING = "/paths"
@vadeg I renamed this to `PATHS`. However, now I feel that the class name `OpenApiPaths` might not appropriate anymore. I was thinking about renaming `OpenApiSections`, what do you think?

2021-03-17 21:56 UTC, vadeg commented on server/zally-core/src/main/kotlin/org/zalando/zally/core/util/OpenApiPaths.kt
> +        const val PATHS_JSON_POINTER_STRING = "/paths"
Good idea.

2021-03-18 06:17 UTC, tharakadesilva commented on server/zally-core/src/main/kotlin/org/zalando/zally/core/util/OpenApiPaths.kt
> +        const val PATHS_JSON_POINTER_STRING = "/paths"
Fixed.

2021-03-18 06:18 UTC, tharakadesilva commented
> Hi @tharakadesilva
> 
> Sorry for the delay. I have left a couple of comments.

Hi @vadeg, thank you for the feedback. I have addressed the comments and I think it is ready for a review again. Thank you for the continuous feedback :)

2021-03-18 18:33 UTC, vadeg approved these changes
@tharakadesilva thank you very much for your contribution!

2021-03-18 18:34 UTC, vadeg commented
👍

2021-04-08 07:00 UTC, tkrop commented
:+1:

2021-04-08 07:00 UTC, merged