Update readme with production deploy instructions
zalando/zally pull request #1389
Opened 2022-05-18 17:11 UTC by bparanj

I have documented the steps needed to deploy zally to a production server. Please review the readme. Fixes issue #1388.

2022-06-14 13:30 UTC, ePaul commented
Your PR didn't actually change the README?

2022-06-24 11:11 UTC, vadeg requested changes

2022-06-24 11:11 UTC, vadeg commented on build-and-run-linode.sh
> +#!/usr/bin/env bash
The script contains the same line as in the build-and-run.sh. What is the purpose of this script?

2022-06-24 11:11 UTC, vadeg commented on build-and-run.sh
> +ZALLY_API_URL=http://34.235.128.99 docker compose up -d
Which IP address is it?

2022-09-05 15:05 UTC, closed without merging